version: '3.4'

services:
  dominosgeolocation.api:
    image: ${DOCKER_REGISTRY-}dominosgeolocationapi
    build:
      context: .
      dockerfile: Api/DominosGeolocation.API/Dockerfile
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "12345678Gy!"
        ACCEPT_EULA: "Y"
    ports:
      - 1433:1433
  dominosgeolocation.insertmq:
    image: ${DOCKER_REGISTRY-}dominosgeolocationinsertmq
    build:
      context: .
      dockerfile: Services/DominosGeolocation.InsertMq/Dockerfile


  dominosgeolocation.consumer:
    image: ${DOCKER_REGISTRY-}dominosgeolocationconsumer
    build:
      context: .
      dockerfile: Services/DominosGeolocation.Consumer/Dockerfile

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - 5672:5672
      - 15672:15672