// <auto-generated />
using System;
using DominosGeolocation.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DominosGeolocation.Data.Migrations
{
    [DbContext(typeof(GeolocationContext))]
    [Migration("20201004122409_geolocation")]
    partial class geolocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DominosGeolocation.Data.Models.DestinationSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DestinationLatitude")
                        .HasColumnName("Destination_latitude")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DestinationLongitude")
                        .HasColumnName("Destination_longitude")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("SourceLatitude")
                        .HasColumnName("Source_latitude")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("SourceLongitude")
                        .HasColumnName("Source_longitude")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DestinationSource");
                });

            modelBuilder.Entity("DominosGeolocation.Data.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DbEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DbStartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDbSuccess")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMqSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("MqEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("MqStartDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("WorkOrder");
                });
#pragma warning restore 612, 618
        }
    }
}
